### ISSUE TITLE
ValueError: not enough values to unpack

### ISSUE THREAD

**Issue by camjac251** [cubrink/LJNormalize#1]
I'm trying to use this script but am running into issues.

I had used srt-parse on a subtitle generated with autosub, which then generated a csv and single wav files (I changed the script's `AudioSegment.from_mp3` to `AudioSegment.from_wav` which worked well).
The csv is formatted like this `66-audio.wav,I mean there's got to be at least one person out there`

However after copying the out.csv to the folder that LJNormalize is in and running the command with Python 3.7.4
`python LJNormalize.py out.csv`
I get this error
```
Traceback (most recent call last):
  File "LJNormalize.py", line 151, in <module>
    filename, text = line
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by cubrink** [comment]
Hey I don't have time to look tonight at the error. The program is sort of
a hack but I'm willing to work on it with you. I made it for my machine, so
I probably forgot some error checking. I should have some time this week.
I'll keep you posted.

Curtis Brinker

**Comment by cubrink** [comment]
`LJNormalize.py` uses the `|` as the delimiting character in `.csv`'s be default so that text doesn't get separated into multiple columns. Try using the `--csv-seperator` flag to set the appropriate delimiter for your file.
